Repository KGCA42-DirectX-Team/Unreal_Team_Portfolio, pull requests merged in 2024-03, with the labels that each got.

#66 Slide, Animation Bug 수정
  Content/Asset/Animation/Characters/Mannequins/Animations/ABP_Manny.uasset
  Content/Blueprints/Character/Player/BP_Player.uasset
  Content/Levels/YWS_TestLevel.umap
  Source/BrutalTakedownSquad/Private/AbilitySystem/Ability/Character/BTS_CharacterCrouchAndSlide.cpp
  Source/BrutalTakedownSquad/Private/AbilitySystem/Ability/Character/BTS_CharacterJumpAndMantle.cpp
  Source/BrutalTakedownSquad/Private/AbilitySystem/Ability/Character/BTS_CharacterSprint.cpp
  Source/BrutalTakedownSquad/Private/Character/Player/BTS_Player.cpp
  Source/BrutalTakedownSquad/Public/AbilitySystem/Ability/Character/BTS_CharacterCrouchAndSlide.h
  Source/BrutalTakedownSquad/Public/AbilitySystem/Ability/Character/BTS_CharacterJumpAndMantle.h
  Source/BrutalTakedownSquad/Public/Character/BTS_CharacterBase.h
  Source/BrutalTakedownSquad/Public/Interface/AnimationEnumInterface.h
Labels: bug fix

#70 AI 블루프린트 에러 수정 및 낙하산 기능추가
  Content/Asset/Armor/Bag/default.uasset
  Content/Asset/Armor/Bag/military_tactical_backpack.uasset
  Content/Asset/Armor/Bag/military_tactical_backpack_texture_0.uasset
  Content/Asset/Armor/Bag/military_tactical_backpack_texture_1.uasset
  Content/Asset/Armor/Bag/military_tactical_backpack_texture_2.uasset
  Content/Asset/parachute/EX_ParachutePlayer_Mesh.uasset
  Content/Asset/parachute/pubg_green_parachute.uasset
  Content/Asset/parachute/pubg_green_parachute_texture_0.uasset
  Content/Asset/parachute/pubg_green_parachute_texture_1.uasset
  Content/Blueprints/AI/AITestBP/BP_AITestGameMode.uasset
  Content/Blueprints/AI/AITestBP/BP_AITestPlayer.uasset
  Content/Blueprints/AI/AITestBP/BP_DeprecatedTestEnemy.uasset
  Content/Blueprints/AI/AITestBP/BP_Enemy.uasset
  Content/Blueprints/AI/AITestBP/BP_TestEnemy.uasset
  Content/Blueprints/AI/AITestBP/BP_TestPlayer.uasset
  Content/Blueprints/AI/BP_TestDismemberPlayer.uasset
  Content/Blueprints/Parachute/BP_Parachute.uasset
  Content/Levels/AiTestMap.umap
  Source/BrutalTakedownSquad/Private/Character/Enemy/BTSEnemyBase.cpp
  West_Heli_UH60A.png
Labels: enhancement, bug fix

#73 ADD Player 3D UI prototype
  Content/Blueprints/UI/HUD/BP_DivisionIconUI.uasset
  Content/Blueprints/UI/HUD/BP_PlayerHUD.uasset
  Content/Blueprints/UI/HUD/BP_PlayerHUD_Division.uasset
  Content/Blueprints/UI/Overlay/WBP_Overlay.uasset
  Content/Blueprints/UI/OverlayWidgetController/BP_OverlayWidgetController.uasset
  Content/Blueprints/UI/ProgressBar/WBP_HPBar.uasset
  Content/Blueprints/UI/ProgressBar/WBP_HealthBar.uasset
  Content/Blueprints/UI/ProgressBar/WBP_ProgressBar.uasset
  Content/Blueprints/UI/ProgressBar/WBP_StaminaBar.uasset
  Content/Blueprints/UI/TestPlayer/5tan.uasset
  Content/Blueprints/UI/TestPlayer/7tan.uasset
  Content/Blueprints/UI/TestPlayer/9tan.uasset
  Content/Blueprints/UI/TestPlayer/BP_TestModeBase.uasset
  Content/Blueprints/UI/TestPlayer/BP_TestUIPlayer.uasset
  Content/Blueprints/UI/TestPlayer/S_Ammo.uasset
  Content/Blueprints/UI/TestPlayer/TestBullet.uasset
  Content/Blueprints/UI/TestPlayer/TestDamage.uasset
  Content/Levels/TestUI.umap
  Source/BrutalTakedownSquad/Private/Character/Player/BTS_Player.cpp
  Source/BrutalTakedownSquad/Private/UI/HUD/BTS_PlayerHUD.cpp
  Source/BrutalTakedownSquad/Private/UI/WidgetController/BTS_OverlayWidgetController.cpp
  Source/BrutalTakedownSquad/Private/UI/WidgetController/BTS_PlayerWidgetController.cpp
  Source/BrutalTakedownSquad/Public/UI/UserWidget/BTS_PlayerUserWidget.h
  Source/BrutalTakedownSquad/Public/UI/WidgetController/BTS_OverlayWidgetController.h
  Source/BrutalTakedownSquad/Public/UI/WidgetController/BTS_PlayerWidgetController.h
Labels: enhancement

#77 낙하산 어빌리티 추가
  Config/DefaultGameplayTags.ini
  Content/Asset/parachute/AM_DiveRoll.uasset
  Content/Asset/parachute/DiveRoll_F.uasset
  Content/Blueprints/AI/AITestBP/BP_AITestGameMode.uasset
  Content/Blueprints/AI/AITestBP/BP_AITestPlayer.uasset
  Content/Blueprints/AI/AITestBP/BP_Enemy.uasset
  Content/Blueprints/AI/BTService/BTService_SetSprint.uasset
  Content/Blueprints/AI/BTTask/BT_Shoot.uasset
  Content/Blueprints/AbilitySystem/Ability/GA_UseParachute.uasset
  Content/Blueprints/AbilitySystem/Effect/GE_Damage.uasset
  Content/Blueprints/Character/Player/BP_Player.uasset
  Content/Blueprints/Input/DA_BTSInputConfig.uasset
  Content/Blueprints/Input/IMC_DefaultCharacterInputContext.uasset
  Content/Blueprints/Input/InputAction/IA_GA_Parachute.uasset
  Content/Blueprints/Item/BP_AR15.uasset
  Content/Blueprints/Item/BP_ArmorComponent.uasset
  Content/Blueprints/Item/BP_Projectile.uasset
  Content/Blueprints/Item/BP_WeaponComponent.uasset
  Content/Levels/AiTestMap.umap
  Content/Levels/BTSMap.umap
  Source/BrutalTakedownSquad/Private/Actor/BTS_ArmorComponent.cpp
  Source/BrutalTakedownSquad/Private/Actor/BTS_WeaponComponent.cpp
  Source/BrutalTakedownSquad/Private/Character/BTS_CharacterBase.cpp
  Source/BrutalTakedownSquad/Private/Character/Enemy/BTSEnemyBase.cpp
  Source/BrutalTakedownSquad/Public/Actor/BTS_ArmorComponent.h
  Source/BrutalTakedownSquad/Public/Actor/BTS_WeaponComponent.h
  Source/BrutalTakedownSquad/Public/Character/BTS_CharacterBase.h
  Source/BrutalTakedownSquad/Public/Character/Enemy/BTSEnemyBase.h
Labels: enhancement

#78 AI 공격 및 AI테스트 플레이어 기능 이관
  Content/Blueprints/AI/AITestBP/BP_AITestGameMode.uasset
  Content/Blueprints/AI/AITestBP/BP_AITestPlayer.uasset
  Content/Blueprints/AI/AITestBP/BP_Enemy.uasset
  Content/Blueprints/AI/BTTask/BT_Shoot.uasset
  Content/Blueprints/AbilitySystem/Ability/GA_UseParachute.uasset
  Content/Blueprints/Character/Player/BP_Player.uasset
  Content/Blueprints/Item/BP_AR15.uasset
  Content/Blueprints/Item/BP_Projectile.uasset
  Content/Blueprints/Item/BP_WeaponComponent.uasset
  Content/Blueprints/Map/MapObject/BP_C4Real.uasset
  Content/Levels/AiTestMap.umap
Labels: enhancement, Change

#80 ADD Equipment UMG Image and Update Inventory
  Content/Blueprints/UI/BP_GameState.uasset
  Content/Blueprints/UI/HUD/BP_PlayerHUD_Division.uasset
  Content/Blueprints/UI/InventoryWidget/BP_InventoryComponent.uasset
  Content/Blueprints/UI/InventoryWidget/Line1.uasset
  Content/Blueprints/UI/InventoryWidget/Tile1.uasset
  Content/Blueprints/UI/InventoryWidget/WBP_Armor.uasset
  Content/Blueprints/UI/InventoryWidget/WBP_EquipSlot.uasset
  Content/Blueprints/UI/InventoryWidget/WBP_Helmet.uasset
  Content/Blueprints/UI/InventoryWidget/WBP_InventoryGridWidget.uasset
  Content/Blueprints/UI/InventoryWidget/WBP_InventoryWidget.uasset
  Content/Blueprints/UI/InventoryWidget/WBP_ItemWidget.uasset
  Content/Blueprints/UI/InventoryWidget/WBP_Weapon.uasset
  Content/Blueprints/UI/Item/BP_AK47.uasset
  Content/Blueprints/UI/Item/BP_AK48.uasset
  Content/Blueprints/UI/Item/BP_AK49.uasset
  Content/Blueprints/UI/Item/BP_AR15_1.uasset
  Content/Blueprints/UI/Item/BP_Grenade.uasset
  Content/Blueprints/UI/Item/BP_Item.uasset
  Content/Blueprints/UI/Item/BP_ItemObject.uasset
  Content/Blueprints/UI/Item/BP_ItemUI.uasset
  Content/Blueprints/UI/Item/BP_Knife.uasset
  Content/Blueprints/UI/TestPlayer/BP_TestModeBase.uasset
  Content/Blueprints/UI/TestPlayer/BP_TestPlayer2.uasset
  Content/Blueprints/UI/TestPlayer/BP_TestPlayerController.uasset
  Content/Blueprints/UI/TestPlayer/BP_TestUIPlayer.uasset
  Content/Levels/TestUI.umap
Labels: enhancement, bug fix

#85 수류탄 충격추가
  Content/Asset/Animation/Mixamo/Backward_Get_Up.uasset
  Content/Asset/Animation/Mixamo/Backward_Get_Up_Montage.uasset
  Content/Asset/Animation/Mixamo/Forward_Get_Up.uasset
  Content/Asset/Animation/Mixamo/Forward_Get_Up_Montage.uasset
  Content/Blueprints/AI/AITestBP/BP_AITestGameMode.uasset
  Content/Blueprints/AI/AITestBP/BP_AITestPlayer.uasset
  Content/Blueprints/AI/AITestBP/BP_Enemy.uasset
  Content/Blueprints/Item/BP_Granade.uasset
  Content/Levels/AiTestMap.umap
Labels: enhancement

#86 ADD weapon table, inventory system overhaul
  Content/Asset/Animation/Characters/Mannequins/Rigs/CR_Mannequin_BasicFootIK.uasset
  Content/Blueprints/Character/Player/BP_Player.uasset
  Content/Blueprints/Item/BP_ActorSpawner.uasset
  Content/Blueprints/Item/BP_WeaponComponent.uasset
  Content/Blueprints/Item/FWeapon.uasset
  Content/Blueprints/Item/WeaponDataTable.uasset
  Content/Blueprints/UI/BP_GameState.uasset
  Content/Blueprints/UI/InventoryWidget/BP_InventoryComponent.uasset
  Content/Blueprints/UI/InventoryWidget/Line1.uasset
  Content/Blueprints/UI/InventoryWidget/Tile1.uasset
  Content/Blueprints/UI/Item/BP_AK47.uasset
  Content/Blueprints/UI/Item/BP_Item.uasset
  Content/Blueprints/UI/Item/BP_ItemObject.uasset
  Content/Levels/ItemTest.umap
  Source/BrutalTakedownSquad/Private/UI/InventoryUI/BTS_InventoryGridWidget.cpp
  Source/BrutalTakedownSquad/Private/UI/InventoryUI/BTS_InventoryWidget.cpp
  Source/BrutalTakedownSquad/Private/UI/InventoryUI/BTS_ItemWidget.cpp
  Source/BrutalTakedownSquad/Private/UI/ItemUI/BTS_ItemObject.cpp
  Source/BrutalTakedownSquad/Public/UI/InventoryUI/BTS_InventoryComponent.h
  Source/BrutalTakedownSquad/Public/UI/InventoryUI/BTS_InventoryGridWidget.h
  Source/BrutalTakedownSquad/Public/UI/InventoryUI/BTS_InventoryWidget.h
  Source/BrutalTakedownSquad/Public/UI/InventoryUI/BTS_ItemWidget.h
  Source/BrutalTakedownSquad/Public/UI/InventoryUI/Line.h
  Source/BrutalTakedownSquad/Public/UI/InventoryUI/Tile.h
  Source/BrutalTakedownSquad/Public/UI/ItemUI/BTS_ItemObject.h
  Source/BrutalTakedownSquad/Public/UI/ItemUI/BTS_ItemUI.h
Labels: enhancement, bug fix

#87 ADD to pause menu and update player 3d HUD
  Content/Blueprints/Input/IMC_DefaultCharacterInputContext.uasset
  Content/Blueprints/Input/InputAction/IA_PauseMenu.uasset
  Content/Blueprints/UI/HUD/BP_PlayerHUD_Division.uasset
  Content/Blueprints/UI/Menu/WBP_MainMenuOption.uasset
  Content/Blueprints/UI/Menu/WBP_PauseMenu.uasset
  Content/Blueprints/UI/TestPlayer/5tan.uasset
  Content/Blueprints/UI/TestPlayer/7tan.uasset
  Content/Blueprints/UI/TestPlayer/9tan.uasset
  Content/Blueprints/UI/TestPlayer/BP_TestPlayer2.uasset
Labels: enhancement, Change

#92 Update Player Bug
  Config/DefaultEngine.ini
  Content/Blueprints/Character/Player/BP_Player.uasset
  Content/Blueprints/UI/TestPlayer/BP_TestPlayer2.uasset
Labels: bug fix

#95 ADD Player 3D HUD Material
  Content/Blueprints/UI/TestPlayer/Widget3DPassThrough_PlayerHUD.uasset
Labels: enhancement

#104 AI 트리 개선 및 엔딩 씬 수정
  Content/Blueprints/AI/BTTask/BT_EvadeGranade.uasset
  Content/Blueprints/AI/BTTask/BT_Shoot.uasset
  Content/Blueprints/AI/BehaviorTree/BT_EnemyBehaviorTree.uasset
  Content/Blueprints/Map/BP_HelicopterRope.uasset
  Content/Blueprints/Map/NewBlueprint.uasset
  Content/Cinematics/PlayerZipLine.uasset
  Content/Levels/AiTestMap.umap
  Content/Levels/BTSMap.umap
  Content/Levels/GameScene/OutroScene.umap
  Source/BrutalTakedownSquad/Private/Map/InteractionObject/BTS_C4.cpp
Labels: bug fix

#105 나침반, 레이더, 데미지 인디케이더, 게임 오버 메뉴 추가
  Content/Asset/Campass/Compass_Marker.uasset
  Content/Asset/Campass/Compass_Points.uasset
  Content/Asset/Minimap/MI_Minimap.uasset
  Content/Asset/Minimap/M_Minimap.uasset
  Content/Asset/Minimap/Minimap.uasset
  Content/Asset/Minimap/PlayerIcon.uasset
  Content/Asset/Minimap/location_Sprite.uasset
  Content/Asset/Minimap/placeholder.uasset
  Content/Blueprints/UI/HUD/BP_PlayerHUD.uasset
  Content/Blueprints/UI/HUD/WBP_HitCircle.uasset
  Content/Blueprints/UI/Menu/WBP_GameOver.uasset
  Content/Blueprints/UI/Overlay/CRT_Raider.uasset
  Content/Blueprints/UI/Overlay/Minimap/AC_PointOfInterest.uasset
  Content/Blueprints/UI/Overlay/Minimap/BC_PointOfInterest.uasset
  Content/Blueprints/UI/Overlay/Minimap/CRT_Raider.uasset
  Content/Blueprints/UI/Overlay/Minimap/CRT_RaiderUserInterface.uasset
  Content/Blueprints/UI/Overlay/Minimap/MI_RaiderUserInterface.uasset
  Content/Blueprints/UI/Overlay/Minimap/MI_RaiderUserInterface1.uasset
  Content/Blueprints/UI/Overlay/Minimap/MPC_Minimap.uasset
  Content/Blueprints/UI/Overlay/Minimap/NewBlueprint.uasset
  Content/Blueprints/UI/Overlay/Minimap/WBP_Campass.uasset
  Content/Blueprints/UI/Overlay/Minimap/WBP_Minimap.uasset
  Content/Blueprints/UI/Overlay/Minimap/WBP_PlayerIcon.uasset
  Content/Blueprints/UI/Overlay/Minimap/WBP_PointOfInterest.uasset
  Content/Blueprints/UI/Overlay/WBP_Minimap.uasset
  Content/Blueprints/UI/Overlay/WBP_Overlay.uasset
  Content/Blueprints/UI/TestPlayer/BP_Player3.uasset
  Content/Blueprints/UI/TestPlayer/BP_TestHeavy.uasset
  Content/Blueprints/UI/TestPlayer/BP_TestModeBase.uasset
  Content/Levels/TestUI.umap
  Source/BrutalTakedownSquad/Private/Character/Player/BTS_Player.cpp
  Source/BrutalTakedownSquad/Public/Character/Player/BTS_Player.h
Labels: enhancement

#107 맵 업데이트 및 ai 개선
  Content/Asset/Animation/Mixamo/AM_ThrowGranade1.uasset
  Content/Asset/Animation/Mixamo/AM_ThrowGranadeAI1.uasset
  Content/Asset/VigilanteContent2/Vehicles/West_Heli_UH60A/BP_West_Heli_UH60A.uasset
  Content/Blueprints/AI/AITestBP/BP_EnemyBase.uasset
  Content/Blueprints/AI/BTTask/BT_EvadeGranade.uasset
  Content/Blueprints/AI/BTTask/BT_Shoot.uasset
  Content/Blueprints/AI/BTTask/BT_ThrowGranade.uasset
  Content/Blueprints/AI/BehaviorTree/BT_EnemyBehaviorTree.uasset
  Content/Blueprints/AI/EQ/EQ_EvadeGranade.uasset
  Content/Blueprints/AirCraft/BP_West_Transport_C130J.uasset
  Content/Blueprints/Item/BP_Granade.uasset
  Content/Blueprints/Map/MapObject/BP_C4Real.uasset
  Content/Blueprints/Map/MapObject/BP_Light.uasset
  Content/Blueprints/Map/NewBlueprint.uasset
  Content/Cinematics/EndingScene.uasset
  Content/Cinematics/PlayerZipLine.uasset
  Content/Cinematics/heliend.uasset
  Content/Levels/AiTestMap.umap
  Content/Levels/BTSMap.umap
  Content/Levels/GameScene/GameStart.umap
  Content/Levels/GameScene/OutroScene.umap
  Source/BrutalTakedownSquad/Private/Map/InteractionObject/BTS_C4.cpp
  Source/BrutalTakedownSquad/Public/Map/InteractionObject/BTS_C4.h
Labels: bug fix, Change

#108 AI 시야범위 변경
  Content/Blueprints/AI/BP_BTSAIController.uasset
Labels: Change

#110 무기 반동, 무기 슬롯
  Content/Asset/Animation/UE5Anim/Rifle_Animation/AnimMantage/AM_RifleFire.uasset
  Content/Asset/Animation/UE5Anim/Rifle_Animation/Fire_Rifle_Ironsights.uasset
  Content/Asset/Armor/ArmorVestIcon.png
  Content/Asset/Armor/ArmorVestIcon.uasset
  Content/Asset/Armor/HelmetIcon.png
  Content/Asset/Armor/HelmetIcon.uasset
  Content/Blueprints/FX/M_GlowingTrails.uasset
  Content/Blueprints/FX/M_Tracer.uasset
  Content/Blueprints/FX/NS_BulletTrails.uasset
  Content/Blueprints/Item/BP_Projectile.uasset
  Content/Blueprints/Item/BP_WeaponComponent.uasset
  Content/Blueprints/Item/IMC_Weapon.uasset
  Content/Blueprints/UI/InventoryWidget/WBP_InventoryGridWidget.uasset
  Content/Blueprints/UI/InventoryWidget/WBP_InventoryWidget.uasset
  Content/Blueprints/UI/InventoryWidget/WBP_ItemWidget.uasset
  Content/Blueprints/UI/InventoryWidget/WBP_Slot.uasset
  Content/Levels/ItemTest.umap
Labels: enhancement

#112 FEAT projectile spawn location to camera, auto shoot
  Content/Asset/Animation/UE5Anim/Rifle_Animation/AnimMantage/AM_RifleFire.uasset
  Content/Blueprints/Character/Player/BP_Player.uasset
  Content/Blueprints/Input/InputAction/IA_Weapon_Shoot.uasset
  Content/Blueprints/Item/BP_Projectile.uasset
  Content/Blueprints/Item/BP_WeaponComponent.uasset
Labels: enhancement, Change

#113 메인메뉴, 옵션 메뉴, 스테미나바, 인벤토리 컴포넌트 수정
  Content/Blueprints/UI/HUD/BP_PlayerHUD_Division.uasset
  Content/Blueprints/UI/Menu/WBP_MainMenu.uasset
  Content/Blueprints/UI/Menu/WBP_MainMenuOption.uasset
  Content/Levels/TestUI.umap
  Source/BrutalTakedownSquad/Private/UI/InventoryUI/BTS_InventoryComponent.cpp
Labels: enhancement, bug fix

#115 ui 버그 수정 및 메인 메뉴, 옵션 메뉴 디자인 변경
  Content/Blueprints/UI/HUD/BP_DivisionIconAmmoUI.uasset
  Content/Blueprints/UI/HUD/BP_DivisionIconGranadeUI.uasset
  Content/Blueprints/UI/HUD/BP_DivisionIconUI.uasset
  Content/Blueprints/UI/HUD/BP_DivisionIconWeaponUI.uasset
  Content/Blueprints/UI/HUD/BP_PlayerHUD_Division.uasset
  Content/Blueprints/UI/HUD/WBP_HitCircle.uasset
  Content/Blueprints/UI/Menu/WBP_MainMenu.uasset
  Content/Blueprints/UI/Menu/WBP_MainMenuOption.uasset
  Content/Blueprints/UI/Overlay/Minimap/WBP_Campass.uasset
  Content/Blueprints/UI/Overlay/Minimap/WBP_Minimap.uasset
  Content/Blueprints/UI/Overlay/Minimap/WBP_PlayerIcon.uasset
  Content/Blueprints/UI/Overlay/Minimap/WBP_PointOfInterest.uasset
  Content/Blueprints/UI/ProgressBar/WBP_HPBar.uasset
  Content/Blueprints/UI/ProgressBar/WBP_ProgressBar.uasset
  Content/Blueprints/UI/ProgressBar/WBP_StaminaBar.uasset
  Content/FPS_HUD/Sprites/Icons/T_Icon_Ammo1.uasset
  Content/FPS_HUD/Sprites/Icons/T_Icon_Settings1.uasset
  Content/FPS_HUD/Sprites/Icons/T_Icon_Weapon_02.uasset
  Content/FPS_HUD/Sprites/Icons/T_Icon_Weapon_06.uasset
  Content/FPS_HUD/Sprites/UI/T_Compass_Arrow1.uasset
  Content/FPS_HUD/Sprites/UI/T_Compass_Points1.uasset
  Content/FPS_HUD/Sprites/UI/T_Menu_Rounded_11.uasset
Labels: bug fix, Change

#117 데미지 변경 및 ai 장전 수정
  Content/Blueprints/AI/AITestBP/BP_EnemyBase.uasset
  Content/Blueprints/AI/BTTask/BT_Shoot.uasset
  Content/Blueprints/AbilitySystem/Attribute/GE_DefaultAttribute1.uasset
  Content/Blueprints/AbilitySystem/Attribute/GE_VitalAttribute1.uasset
  Content/Blueprints/Item/BP_Granade.uasset
  Content/Blueprints/Map/MapObject/BP_C4Real.uasset
  Content/Levels/AiTestMap.umap
  Content/Levels/BTSMap.umap
  Source/BrutalTakedownSquad/Private/Map/InteractionObject/BTS_C4.cpp
  Source/BrutalTakedownSquad/Public/Map/InteractionObject/BTS_C4.h
Labels: bug, Change

#119 AI 데미지 퍼셉션 추가
  Content/Blueprints/AI/BP_BTSAIController.uasset
  Content/Blueprints/AI/BTTask/BT_Shoot.uasset
  Content/Blueprints/Item/BP_Projectile.uasset
  Source/BrutalTakedownSquad/Private/Character/Enemy/BTSAIController.cpp
Labels: enhancement

#120 나침반 오류 수정 및 이미지 교체와 프로그래스 바 오류 수정
  Content/Blueprints/Test/BP_Health.uasset
  Content/Blueprints/UI/HUD/BP_PlayerHUD_Division.uasset
  Content/Blueprints/UI/HUD/WBP_HitCircle.uasset
  Content/Blueprints/UI/Menu/WBP_GameOver.uasset
  Content/Blueprints/UI/Menu/WBP_PauseMenu.uasset
  Content/Blueprints/UI/Overlay/Minimap/WBP_Campass.uasset
  Content/Blueprints/UI/ProgressBar/WBP_HPBar.uasset
  Content/Blueprints/UI/ProgressBar/WBP_ProgressBar.uasset
  Content/Blueprints/UI/ProgressBar/WBP_StaminaBar.uasset
  Content/Levels/TestUI.umap
Labels: bug fix, Change

#121 라이플 애니메이션 추가 및 웨폰컴포넌트 사본 추가
  Content/Asset/FPS_Weapon_Bundle/Weapons/Meshes/AR4/AR4_Animation.uasset
  Content/Asset/FPS_Weapon_Bundle/Weapons/Meshes/AR4/SK_AR4_Skeleton.uasset
  Content/Asset/FPS_Weapon_Bundle/Weapons/Meshes/AR4/SK_AR4_Skeleton_Sequence.uasset
  Content/Blueprints/AI/AITestBP/BP_EnemyBase.uasset
  Content/Blueprints/AI/BTTask/BT_Shoot.uasset
  Content/Blueprints/AI/BehaviorTree/BT_EnemyBehaviorTree.uasset
  Content/Blueprints/Item/BP_Granade.uasset
  Content/Blueprints/Item/BP_WeaponComponent1.uasset
  Content/Blueprints/Map/MapObject/BP_Floor.uasset
  Content/Blueprints/Map/MapObject/BP_Wall.uasset
  Content/Blueprints/Utility/Ar5Texture.uasset
  Content/Blueprints/Utility/BP_Baker.uasset
  Content/Blueprints/Utility/BP_ImageCapture.uasset
  Content/Blueprints/Utility/MI_AR4.uasset
  Content/Blueprints/Utility/RT_Portrait.uasset
  Content/Blueprints/Utility/RT_Portrait_Tex.uasset
  Content/FPS_HUD/Sprites/Icons/RT_Portrait.uasset
  Content/Levels/AiTestMap.umap
  Content/Levels/BTSMap.umap
  Content/Megascans/3D_Assets/Modular_Handrail_Kit_wjnffhxdw/S_Modular_Handrail_Kit_wjnffhxdw_lod5_Var1.uasset
  Content/Megascans/3D_Assets/Modular_Wooden_Railing_End_Post_ue3qfikdw/S_Modular_Wooden_Railing_End_Post_ue3qfikdw_lod5_Var1.uasset
  Source/BrutalTakedownSquad/Private/Character/Enemy/BTSAIController.cpp
Labels: enhancement, Change

#126 사운드 설정 추가, 옵션 변경 저장 불러오기 추가
  Content/Asset/Minimap/Enemy.uasset
  Content/Asset/Minimap/Player.uasset
  Content/Asset/Minimap/PlayerIcon.uasset
  Content/Asset/Minimap/location_Sprite.uasset
  Content/Asset/Minimap/placeholder.uasset
  Content/Asset/Minimap/play.uasset
  Content/Blueprints/AI/AITestBP/BP_Heavy.uasset
  Content/Blueprints/AI/AITestBP/BP_Normal.uasset
  Content/Blueprints/UI/Menu/Sound/SCM_MasterVolume.uasset
  Content/Blueprints/UI/Menu/WBP_MainMenu.uasset
  Content/Blueprints/UI/Menu/WBP_MainMenuOption.uasset
  Content/Blueprints/UI/Menu/WBP_PauseMenu.uasset
  Content/Blueprints/UI/Overlay/Minimap/WBP_PlayerIcon.uasset
  Content/Blueprints/UI/Overlay/Minimap/WBP_PointOfInterest.uasset
  Content/Blueprints/UI/Overlay/WBP_Overlay.uasset
  Content/Blueprints/UI/ProgressBar/WBP_ProgressBar.uasset
  Content/Blueprints/UI/ProgressBar/WBP_StaminaBar.uasset
  Content/Levels/TestUI.umap
Labels: enhancement

#129 패키징 버그
  Build/Windows/FileOpenOrder/CookerOpenOrder.log
  Build/Windows/FileOpenOrder/EditorOpenOrder.log
  Config/DefaultEngine.ini
  Config/DefaultGame.ini
  Content/Asset/Animation/ABP_Manny.uasset
  Content/Blueprints/AI/AITestBP/BP_AITestPlayer.uasset
  Content/Blueprints/AI/AITestBP/BP_EnemyBase.uasset
  Content/Blueprints/AbilitySystem/Ability/Deprecated/GA_ChangePerspective.uasset
  Content/Blueprints/AbilitySystem/Ability/Deprecated/GA_Character_Reload.uasset
  Content/Blueprints/AbilitySystem/Ability/Deprecated/GA_Character_Shoot.uasset
  Content/Blueprints/AbilitySystem/Ability/Deprecated/GA_EndJump.uasset
  Content/Blueprints/AbilitySystem/Ability/Deprecated/GA_FirstAid.uasset
  Content/Blueprints/AbilitySystem/Ability/Deprecated/GA_PickUP.uasset
  Content/Blueprints/AbilitySystem/Ability/Deprecated/GA_Weapon_ADS.uasset
  Content/Blueprints/AbilitySystem/Ability/Deprecated/GA_Weapon_Shoot.uasset
  Content/Blueprints/AbilitySystem/Effect/GE_SteminaRegen.uasset
  Content/Blueprints/Character/Player/BP_Player.uasset
  Content/Blueprints/Character/Player/BP_TestProjectile.uasset
  Content/Blueprints/Character/Player/BP_TestWeapon.uasset
  Content/Blueprints/Item/BP_BodyArmor.uasset
  Content/Blueprints/Item/BP_Grenade.uasset
  Content/Blueprints/Item/Deprecated/BP_AR15.uasset
  Content/Blueprints/Item/Deprecated/DeprecatedGranade.uasset
  Content/Blueprints/Test/BP_Health.uasset
  Content/Blueprints/Test/BP_Stamina.uasset
  Content/Blueprints/Test/BP_TestDefensePower.uasset
  Content/Blueprints/Test/BP_TestDuration.uasset
  Content/Blueprints/Test/BP_TestInfinite.uasset
  Content/Blueprints/Test/BP_TestInstant.uasset
  Content/Blueprints/Test/BT_TestEffectActor.uasset
  Content/Blueprints/UI/InventoryWidget/Deprecated_WBP_ArmorSlot.uasset
  Content/Blueprints/UI/InventoryWidget/Deprecated_WBP_EquipSlot.uasset
  Content/Blueprints/UI/InventoryWidget/Deprecated_WBP_Weapon.uasset
  Content/Blueprints/UI/InventoryWidget/Deprecated_WBP_WeaponSlot.uasset
  Content/Blueprints/UI/TestPlayer/5tan.uasset
  Content/Blueprints/UI/TestPlayer/7tan.uasset
  Content/Blueprints/UI/TestPlayer/9tan.uasset
  Content/Blueprints/UI/TestPlayer/BP_Player3.uasset
  Content/Blueprints/UI/TestPlayer/BP_TestHeavy.uasset
  Content/Blueprints/UI/TestPlayer/BP_TestModeBase.uasset
  Content/Blueprints/UI/TestPlayer/BP_TestPlayer2.uasset
  Content/Blueprints/UI/TestPlayer/BP_TestPlayerController.uasset
  Content/Blueprints/UI/TestPlayer/TestBullet.uasset
  Content/Blueprints/UI/TestPlayer/TestDamage.uasset
  Content/Levels/AiTestMap.umap
  Content/Levels/YWS_TestLevel.umap
  Source/BrutalTakedownSquad/Private/Character/BTS_CharacterBase.cpp
  Source/BrutalTakedownSquad/Private/Character/Player/BTS_Player.cpp
  Source/BrutalTakedownSquad/Public/Character/BTS_CharacterBase.h
Labels: bug fix

#132 Update map's key to Fname
  Config/DefaultEngine.ini
  Content/Asset/UI/TarkovUI.png
  Content/Asset/UI/TarkovUI.uasset
  Content/Blueprints/Character/Player/BP_Player.uasset
  Content/Blueprints/UI/InventoryWidget/BP_InventoryComponent.uasset
  Source/BrutalTakedownSquad/Private/UI/InventoryUI/BTS_InventoryComponent.cpp
  Source/BrutalTakedownSquad/Public/UI/InventoryUI/BTS_InventoryComponent.h
Labels: Change

#133 반동, 퀘스트 추가
  Content/Asset/Animation/ABP_Manny.uasset
  Content/Blueprints/Game/BP_GameModeBase.uasset
  Content/Blueprints/Quest/BP_C4Complete.uasset
  Content/Blueprints/Quest/BP_C4Entry.uasset
  Content/Blueprints/Quest/BP_C4Progress.uasset
  Content/Blueprints/Quest/BP_C4Quest.uasset
  Content/Data/AnimData/ADSTimeCurve.uasset
  Content/Levels/YWS_TestLevel.umap
  Source/BrutalTakedownSquad/Private/Quest/BTS_Quest.cpp
  Source/BrutalTakedownSquad/Private/Quest/BTS_QuestState.cpp
  Source/BrutalTakedownSquad/Private/Quest/C4Quest/BTS_QuestStateC4Completed.cpp
  Source/BrutalTakedownSquad/Private/Quest/C4Quest/BTS_QuestStateC4Entry.cpp
  Source/BrutalTakedownSquad/Private/Quest/C4Quest/BTS_QuestStateC4Progress.cpp
  Source/BrutalTakedownSquad/Public/Quest/BTS_Quest.h
  Source/BrutalTakedownSquad/Public/Quest/BTS_QuestState.h
  Source/BrutalTakedownSquad/Public/Quest/C4Quest/BTS_QuestStateC4Completed.h
  Source/BrutalTakedownSquad/Public/Quest/C4Quest/BTS_QuestStateC4Entry.h
  Source/BrutalTakedownSquad/Public/Quest/C4Quest/BTS_QuestStateC4Progress.h
Labels: enhancement, bug fix

#134 AI 로직 수정 및 해체 아이템 사운드 및 모션 추가
  Build/Windows/FileOpenOrder/CookerOpenOrder.log
  Build/Windows/FileOpenOrder/EditorOpenOrder.log
  Content/Asset/Animation/Mixamo/AM_Interaction.uasset
  Content/Asset/Animation/Mixamo/Falling_UE.uasset
  Content/Asset/Animation/Mixamo/Interaction.uasset
  Content/Asset/Animation/Mixamo/StandingTorchLightTorch_UE.uasset
  Content/Asset/Map/박스_브러시_StaticMesh.uasset
  Content/Asset/MilitaryWeapSilver/Sound/Rifle/Cues/RifleA_Fire_Cue.uasset
  Content/Asset/MilitaryWeapSilver/Sound/Rifle/Wavs/RifleA_Fire06.uasset
  Content/Asset/Sound/UI-Data-Loading-Sound-Effect-_mp3cut_net_.uasset
  Content/Blueprints/AI/AITestBP/BP_EnemyBase.uasset
  Content/Blueprints/AI/BP_BTSAIController.uasset
  Content/Blueprints/AI/BTTask/BT_Shoot.uasset
  Content/Blueprints/Character/Player/BP_Player.uasset
  Content/Blueprints/Item/BP_C4CaseNew.uasset
  Content/Blueprints/Item/BP_Grenade.uasset
  Content/Blueprints/Map/HideStructure/BP_Sandbag.uasset
  Content/Blueprints/Map/MapObject/BP_C4Real.uasset
  Content/Blueprints/Map/MapObject/BP_Floor.uasset
  Content/Levels/AiTestMap.umap
  Content/Levels/BTSMap.umap
  Content/Levels/GameScene/OutroScene.umap
  Source/BrutalTakedownSquad/Private/Map/InteractionObject/BTS_C4.cpp
  Source/BrutalTakedownSquad/Public/Character/Enemy/BTSAIController.h
  Source/BrutalTakedownSquad/Public/Map/InteractionObject/BTS_C4.h
Labels: enhancement, Change

#135 여러가지 추가했어요
  Content/Blueprints/Item/BP_Projectile.uasset
  Content/Blueprints/UI/HUD/BP_PlayerHUD_Division.uasset
  Content/Blueprints/UI/HUD/WBP_Ammo5Inventory.uasset
  Content/Blueprints/UI/HUD/WBP_CurrentAmmo5.uasset
  Content/Blueprints/UI/HUD/WBP_HitCircle.uasset
  Content/Blueprints/UI/InventoryWidget/Trapezoid_svg.uasset
  Content/Blueprints/UI/InventoryWidget/WBP_EquipSlot.uasset
  Content/Blueprints/UI/Menu/WBP_MainMenuOption.uasset
  Content/Blueprints/UI/Menu/WBP_PauseMenu.uasset
  Content/FPS_HUD/Sprites/Icons/T_Icon_Weapon_07.uasset
  Content/Levels/TestUI.umap
  Source/BrutalTakedownSquad/Private/UI/WidgetController/BTS_OverlayWidgetController.cpp
  Source/BrutalTakedownSquad/Public/UI/WidgetController/BTS_OverlayWidgetController.h
Labels: enhancement, bug fix

#136 폭발 3D사운드 추가
  Content/Asset/Map/Block.uasset
  Content/Blueprints/AI/BehaviorTree/BT_EnemyBehaviorTree.uasset
  Content/Blueprints/Item/BP_Grenade.uasset
  Content/Blueprints/Map/MapObject/BP_C4Real.uasset
  Content/Levels/BTSMap.umap
Labels: Change

#137 Update inventory UI slot
  Config/DefaultGameplayTags.ini
  Content/Asset/UI/TransparentImage.uasset
  Content/Blueprints/Character/Player/BP_Player.uasset
  Content/Blueprints/UI/InventoryWidget/BP_InventoryComponent.uasset
  Content/Blueprints/UI/InventoryWidget/WBP_InventoryWidget.uasset
  Content/Blueprints/UI/InventoryWidget/W_Inventory_Main.uasset
  Content/Blueprints/UI/InventoryWidget/W_ItemWidget.uasset
  Source/BrutalTakedownSquad/Private/UI/InventoryUI/BTS_InventoryComponent.cpp
  Source/BrutalTakedownSquad/Public/UI/InventoryUI/BTS_InventoryComponent.h
  Source/BrutalTakedownSquad/Public/UI/ItemUI/BTS_ItemObject.h
Labels: enhancement

#139 재장전 버그 수정, 발사 로직 수정
  Content/Asset/FPS_Weapon_Bundle/Weapons/Meshes/AR4/SK_AR4_Skeleton.uasset
  Content/Asset/FPS_Weapon_Bundle/Weapons/Meshes/AR4/SK_AR4_X.uasset
  Content/Asset/FPS_Weapon_Bundle/Weapons/Meshes/AR4/SK_AR4_X_Skeleton.uasset
  Content/Blueprints/AbilitySystem/Effect/GE_DecreaseAmmo5.uasset
  Content/Blueprints/Item/BP_WeaponComponent.uasset
Labels: enhancement

#141 press any key, ending credit 메뉴 추가
  Content/Blueprints/AI/AITestBP/BP_AITestGameMode.uasset
  Content/Blueprints/UI/Menu/WBP_EndingCredit.uasset
  Content/Blueprints/UI/Menu/WBP_MainMenu.uasset
  Content/Blueprints/UI/Menu/WBP_PressAnyKey.uasset
  Content/Levels/GameScene/GameStart.umap
  Content/Levels/TestGameStart.umap
Labels: Change

#142 FIx Interaction Notify
  Content/Asset/Animation/Mixamo/AM_Interaction.uasset
  Content/Blueprints/Character/Player/BP_Player.uasset
  Content/Levels/BTSMap.umap
Labels: Change

#146 ADD Quest UI
  Content/Blueprints/UI/Overlay/Quset/WBP_QuestText.uasset
  Content/Blueprints/UI/Overlay/WBP_Overlay.uasset
Labels: enhancement

#148 FIX swap failure
  Content/Asset/AxeWield/AS_SwapWeapon_Montage.uasset
  Content/Asset/AxeWield/AxeSwing_Montage.uasset
  Content/Asset/Characters/Mannequins/Meshes/SK_Mannequin.uasset
  Content/Blueprints/Input/IMC_DefaultCharacterInputContext.uasset
  Content/Blueprints/Input/IMC_Gun.uasset
  Content/Blueprints/Input/IMC_Melee.uasset
  Content/Blueprints/Item/Animation/AM_DrawWeapon.uasset
  Content/Blueprints/Item/BP_WeaponComponent.uasset
Labels: bug, bug fix

#149 FIX AI Weapon
  Content/Blueprints/AI/AITestBP/BP_EnemyBase.uasset
  Content/Blueprints/AI/BTTask/BT_Shoot.uasset
  Content/Blueprints/AI/BehaviorTree/BT_EnemyBehaviorTree.uasset
  Content/Blueprints/AI/EQ/EQ_EvadeGranade.uasset
  Content/Blueprints/Character/Player/BP_Player.uasset
  Content/Blueprints/Item/BP_Ammo.uasset
  Content/Blueprints/Item/BP_FirstAidInstaceEffect.uasset
  Content/Levels/AiTestMap.umap
  Content/Levels/BTSMap.umap
Labels: bug fix

#152 제발 돼라
  Content/Asset/Sound/click-21156.uasset
  Content/Asset/Sound/mixkit-classic-click-1117.uasset
  Content/Blueprints/AI/AITestBP/BP_EnemyBase.uasset
  Content/Blueprints/Character/Player/BP_Player.uasset
  Content/Blueprints/UI/InventoryWidget/WBP_InventoryWidget.uasset
  Content/Blueprints/UI/InventoryWidget/W_Inventory_Main.uasset
  Content/Blueprints/UI/InventoryWidget/W_ItemWidget.uasset
  Content/Blueprints/UI/Menu/Sound/BP_SaveSound.uasset
  Content/Blueprints/UI/Menu/WBP_GameOver.uasset
  Content/Blueprints/UI/Menu/WBP_MainMenu.uasset
  Content/Blueprints/UI/Menu/WBP_MainMenuOption.uasset
  Content/Blueprints/UI/Menu/WBP_PauseMenu.uasset
  Content/Blueprints/UI/Menu/WBP_PressAnyKey.uasset
  Content/Blueprints/UI/Overlay/Minimap/AC_PointOfInterest.uasset
  Content/Blueprints/UI/Overlay/Minimap/WBP_PlayerIcon.uasset
  Content/Blueprints/UI/Overlay/Quset/WBP_QuestText.uasset
  Content/Blueprints/UI/Overlay/WBP_Overlay.uasset
  Content/Levels/GameScene/GameStart.umap
  Content/Levels/TestGameStart.umap
  Content/Levels/TestUI.umap
Labels: enhancement, bug fix

#154 AI 다시수정
  Content/Blueprints/AI/AITestBP/BP_EnemyBase.uasset
  Content/Blueprints/AI/EQ/EQ_EvadeGranade.uasset
  Content/Blueprints/Character/Player/BP_Player.uasset
  Content/Blueprints/Item/BP_Grenade.uasset
  Content/Cinematics/EndMaster.uasset
  Content/Levels/BTSMap.umap
Labels: Change

#155 1차 최종본
  Config/DefaultGame.ini
  Content/Asset/Animation/ABP_Manny.uasset
  Content/Asset/AxeWield/AS_SwapWeapon_Montage.uasset
  Content/Asset/AxeWield/AxeSwing_Montage.uasset
  Content/Asset/Map/Painted_Pulaski_Axe_wlkkdci/SK/AxeBone_1_Skeleton.uasset
  Content/Blueprints/AbilitySystem/Ability/Active/GA_MeleeAttack.uasset
  Content/Blueprints/AbilitySystem/Effect/GE_MeleeDamage.uasset
  Content/Blueprints/Character/Player/BP_Player.uasset
  Content/Blueprints/Game/BP_GameModeBase.uasset
  Content/Blueprints/Input/DA_BTSInputConfig.uasset
  Content/Blueprints/Item/BP_WeaponComponent.uasset
  Content/Blueprints/Quest/BP_C4Complete.uasset
  Content/Blueprints/Quest/BP_C4Progress.uasset
  Content/Blueprints/Quest/BP_C4Quest.uasset
  Content/Blueprints/UI/HUD/BP_PlayerHUD_Division.uasset
  Content/Blueprints/UI/InventoryWidget/W_Inventory_Main.uasset
  Content/Blueprints/UI/Overlay/Quset/WBP_QuestText.uasset
  Content/Blueprints/UI/Overlay/WBP_Overlay.uasset
  Content/Levels/BTSMap.umap
  Content/Levels/YWS_TestLevel.umap
  Source/BrutalTakedownSquad/Private/AbilitySystem/Ability/Character/BTS_CharacterJumpAndMantle.cpp
  Source/BrutalTakedownSquad/Private/Character/Player/BTS_Player.cpp
  Source/BrutalTakedownSquad/Public/Quest/BTS_Quest.h
Labels: enhancement

#156 총 이미지 개선 및 미니맵 수정
  Content/Asset/FPS_Weapon_Bundle/Weapons/TempWeaponImage/AR4_Image.uasset
  Content/Asset/FPS_Weapon_Bundle/Weapons/TempWeaponImage/MI_AR4.uasset
  Content/Asset/FPS_Weapon_Bundle/Weapons/TempWeaponImage/M_Icon_AR4.uasset
  Content/Blueprints/AI/AITestBP/BP_Heavy.uasset
  Content/Blueprints/Character/Player/BP_Player.uasset
  Content/Blueprints/UI/HUD/BP_PlayerHUD_Division.uasset
  Content/Blueprints/UI/InventoryWidget/W_Inventory_Main.uasset
  Content/Blueprints/UI/InventoryWidget/W_ItemWidget.uasset
  Content/Blueprints/UI/Menu/WBP_EndingCredit.uasset
  Content/Blueprints/UI/Menu/WBP_GameOver.uasset
  Content/Blueprints/UI/Overlay/Minimap/CRT_Raider.uasset
  Content/Blueprints/UI/Overlay/Minimap/WBP_PointOfInterest.uasset
  Content/Blueprints/Utility/Deprecated_Ar4Texture.uasset
Labels: enhancement, Change
