Repository KGCA42-DirectX-Team/Unreal_Team_Portfolio, pull requests merged in 2024-02, with the labels that each got.

#4 AddMap
  README.md
Labels: enhancement

#5 Create TestUI.umap
  Content/Levels/TestUI.umap
Labels: enhancement

#7 Make Building Only Outside
  Content/Levels/BTSMap.umap
  Content/ModularBuildingSet/Meshes/Store_Upper_Wndws/windows_building_upper_4x1_a.uasset
  Content/ModularBuildingSet/Meshes/Store_Upper_Wndws/windows_building_upper_4x1_b.uasset
  Content/ModularBuildingSet/Meshes/Store_Upper_Wndws/windows_building_upper_4x1_c.uasset
  Content/ModularBuildingSet/Meshes/Store_Upper_Wndws/windows_building_upper_4x1_d.uasset
  Content/ModularBuildingSet/Meshes/Store_Upper_Wndws/windows_building_upper_5x1_a.uasset
  Content/ModularBuildingSet/Meshes/Store_fronts/store_front_door_4x1_a.uasset
  Content/ModularBuildingSet/Meshes/Store_fronts/store_front_windows_broken_4x1_a.uasset
  Content/ModularBuildingSet/Meshes/Store_fronts/store_front_windows_broken_4x1_c.uasset
  Content/ModularBuildingSet/Meshes/Store_fronts/store_front_windows_intact_4x1_b.uasset
  Content/ModularBuildingSet/RealBuliding.uasset
  Content/ModularBuildingSet/RefBuilding.FBX
  Content/ModularBuildingSet/RefBuilding.uasset
  Content/ModularBuildingSet/materials/Bricks_Tiles/brick_wall_dark_red.uasset
  Content/ModularBuildingSet/materials/Bricks_Tiles/brick_wall_red.uasset
  Content/ModularBuildingSet/materials/Bricks_Tiles/tile_trim___default.uasset
  Content/ModularBuildingSet/materials/Concrete/concrete_trim.uasset
  Content/ModularBuildingSet/materials/Ground_Rubble/ground_gravel_dirt.uasset
  Content/ModularBuildingSet/materials/Metal/metal_shutters.uasset
  Content/ModularBuildingSet/materials/Metal/metal_trim___default.uasset
  Content/ModularBuildingSet/materials/black_interior.uasset
  Content/ModularBuildingSet/materials/black_interior2.uasset
Labels: enhancement

#9 Add Default Player
  Config/DefaultEngine.ini
  Config/DefaultInput.ini
  Content/Blueprint/AbilitySystem/GE_DefaultAttribute.uasset
  Content/Blueprint/Character/Player/BP_Player.uasset
  Content/Blueprint/Character/Player/BP_PlayerController.uasset
  Content/Blueprint/Character/Player/BP_PlayerState.uasset
  Content/Blueprint/Game/BP_BTSGameMode.uasset
  Content/Blueprint/Input/DA_BTSInputConfig.uasset
  Content/Blueprint/Input/IMC_BTSInputContext.uasset
  Content/Blueprint/Input/InputAction/IA_1.uasset
  Content/Blueprint/Input/InputAction/IA_2.uasset
  Content/Blueprint/Input/InputAction/IA_3.uasset
  Content/Blueprint/Input/InputAction/IA_4.uasset
  Content/Blueprint/Input/InputAction/IA_LMB.uasset
  Content/Blueprint/Input/InputAction/IA_Look.uasset
  Content/Blueprint/Input/InputAction/IA_Move.uasset
  Content/Blueprint/Input/InputAction/IA_RMB.uasset
  Content/Blueprint/Input/InputAction/IA_Space.uasset
  Content/Levels/YWS_TestLevel.umap
  Source/BrutalTakedownSquad/BTSGameplayTags.cpp
  Source/BrutalTakedownSquad/BTSGameplayTags.h
  Source/BrutalTakedownSquad/Private/AbilitySystem/BTSAbilitySystemComponent.cpp
  Source/BrutalTakedownSquad/Private/AbilitySystem/BTSAttributeSet.cpp
  Source/BrutalTakedownSquad/Private/AbilitySystem/Data/AttributeInfo.cpp
  Source/BrutalTakedownSquad/Private/Character/BTSCharacterBase.cpp
  Source/BrutalTakedownSquad/Private/Character/Player/BTSPlayer.cpp
  Source/BrutalTakedownSquad/Private/Character/Player/BTSPlayerController.cpp
  Source/BrutalTakedownSquad/Private/Character/Player/BTSPlayerState.cpp
  Source/BrutalTakedownSquad/Private/Input/BTSInputConfig.cpp
  Source/BrutalTakedownSquad/Public/AbilitySystem/Ability/BTSGameplayAbility.h
  Source/BrutalTakedownSquad/Public/AbilitySystem/BTSAbilitySystemComponent.h
  Source/BrutalTakedownSquad/Public/AbilitySystem/BTSAttributeSet.h
  Source/BrutalTakedownSquad/Public/AbilitySystem/Data/AttributeInfo.h
  Source/BrutalTakedownSquad/Public/Character/BTSCharacterBase.h
  Source/BrutalTakedownSquad/Public/Character/Player/BTSPlayer.h
  Source/BrutalTakedownSquad/Public/Character/Player/BTSPlayerController.h
  Source/BrutalTakedownSquad/Public/Character/Player/BTSPlayerState.h
  Source/BrutalTakedownSquad/Public/Input/BTSInputComponent.h
  Source/BrutalTakedownSquad/Public/Input/BTSInputConfig.h
Labels: bug, enhancement

#8 Add Building 1stFloor
  Content/Levels/BTSMap.umap
  Content/ModularBuildingSet/BP_Floor.uasset
  Content/ModularBuildingSet/BP_Wall.uasset
  Content/ModularBuildingSet/materials/Bricks_Tiles/brick_wall_grey.uasset
  Content/ModularBuildingSet/materials/Bricks_Tiles/bricks_red.uasset
Labels: enhancement

#10 566 총알 추가 (테스트 단계)
  Content/Blueprints/Weapon/BP_Bullet_556.uasset
  Content/FPS_Weapon_Bundle/Maps/Weapons_Showcase.umap
  Content/Levels/ItemTestLevel.umap
  Source/BrutalTakedownSquad/Private/Actor/ABTSProjectile.cpp
  Source/BrutalTakedownSquad/Public/Actor/ABTSProjectile.h
Labels: enhancement

#14 건물 3층 4층 추가
  Content/Levels/BTSMap.umap
Labels: enhancement

#15 Jump, Sprint Ability 추가
  Content/Asset/Animation/Characters/Mannequins/Animations/ABP_Manny.uasset
  Content/Blueprints/AbilitySystem/Ability/GA_CharacterJump.uasset
  Content/Blueprints/AbilitySystem/Ability/GA_CharacterSprint.uasset
  Content/Blueprints/AbilitySystem/Attribute/GE_DefaultAttribute.uasset
  Content/Blueprints/AbilitySystem/Attribute/GE_VitalAttribute.uasset
  Content/Blueprints/AbilitySystem/GE_DefaultAttribute.uasset
  Content/Blueprints/AbilitySystem/GE_VitalAttribute.uasset
  Content/Blueprints/Character/Player/BP_Player.uasset
  Content/Blueprints/Input/DA_BTSInputConfig.uasset
  Content/Blueprints/Input/IMC_BTSInputContext.uasset
  Content/Blueprints/Input/InputAction/IA_C.uasset
  Content/Blueprints/Input/InputAction/IA_Shift.uasset
  Content/Blueprints/Input/InputAction/IA_Space.uasset
  Content/Enum/E_Movement_Input.uasset
  Source/BrutalTakedownSquad/Private/AbilitySystem/Ability/BTSCharacterJump.cpp
  Source/BrutalTakedownSquad/Private/AbilitySystem/Ability/BTSCharacterSprint.cpp
  Source/BrutalTakedownSquad/Private/BTSGameplayTags.cpp
  Source/BrutalTakedownSquad/Public/AbilitySystem/Ability/BTSCharacterJump.h
  Source/BrutalTakedownSquad/Public/AbilitySystem/Ability/BTSCharacterSprint.h
  Source/BrutalTakedownSquad/Public/AbilitySystem/Ability/BTSGameplayAbility.h
  Source/BrutalTakedownSquad/Public/AbilitySystem/BTSAttributeSet.h
  Source/BrutalTakedownSquad/Public/BTSGameplayTags.h
  Source/BrutalTakedownSquad/Public/Character/BTSCharacterBase.h
Labels: enhancement

#16 AI Controller 및 BehaviorTree 추가
  BrutalTakedownSquad.uproject
  Content/Blueprints/AI/BB_EnemyBlackboard.uasset
  Content/Blueprints/AI/BP_BTSAIController.uasset
  Content/Blueprints/AI/BP_BTSEnemy.uasset
  Content/Blueprints/AI/BTS_FindNearestPlayer.uasset
  Content/Blueprints/AI/BT_EnemyBehaviorTree.uasset
  Content/Blueprints/AI/BT_GetRandomLocation.uasset
  Content/Blueprints/AI/EQ_PatrollLocation.uasset
  Content/Levels/AiTestMap.umap
  Content/Levels/BTSMap.umap
  Content/Levels/YWS_TestLevel.umap
  Content/Megascans/3D_Assets/Concrete_Stairs_uknjfevga/S_Concrete_Stairs_uknjfevga_lod5_Var1.uasset
  Source/BrutalTakedownSquad/BrutalTakedownSquad.Build.cs
  Source/BrutalTakedownSquad/Private/Character/Enemy/BTSAIController.cpp
  Source/BrutalTakedownSquad/Private/Character/Enemy/BTSEnemyBase.cpp
  Source/BrutalTakedownSquad/Private/Character/Enemy/BTS_BTService_FindNearestPlayer.cpp
  Source/BrutalTakedownSquad/Public/Character/Enemy/BTSAIController.h
  Source/BrutalTakedownSquad/Public/Character/Enemy/BTSEnemyBase.h
  Source/BrutalTakedownSquad/Public/Character/Enemy/BTS_BTService_FindNearestPlayer.h
Labels: enhancement

#18 Crouch, Change Perspectvie 능력 추가
  Content/Asset/Animation/Characters/Mannequins/Animations/ABP_Manny.uasset
  Content/Asset/Animation/Lyra_Anim/Unarmed_Animation/MM_Unarmed_Jump_RecoveryAdditive.uasset
  Content/Blueprints/AbilitySystem/Ability/GA_CharacterCrouch.uasset
  Content/Blueprints/AbilitySystem/Ability/GA_PlayerChagePerspective.uasset
  Content/Blueprints/Character/Player/BP_Player.uasset
  Content/Blueprints/Input/DA_BTSInputConfig.uasset
  Content/Blueprints/Input/IMC_BTSInputContext.uasset
  Content/Blueprints/Input/InputAction/IA_B.uasset
  Content/Blueprints/Input/InputAction/IA_C.uasset
  Content/Blueprints/Input/InputAction/IA_Space.uasset
  Content/Levels/YWS_TestLevel.umap
  Source/BrutalTakedownSquad/Private/AbilitySystem/Ability/BTSCharacterCrouch.cpp
  Source/BrutalTakedownSquad/Private/AbilitySystem/Ability/BTSCharacterJump.cpp
  Source/BrutalTakedownSquad/Private/AbilitySystem/Ability/BTSPlayerChangePerspective.cpp
  Source/BrutalTakedownSquad/Private/BTSGameplayTags.cpp
  Source/BrutalTakedownSquad/Private/Game/BTSGameModeBase.cpp
  Source/BrutalTakedownSquad/Private/Input/BTSInputComponent.cpp
  Source/BrutalTakedownSquad/Public/AbilitySystem/Ability/BTSCharacterCrouch.h
  Source/BrutalTakedownSquad/Public/AbilitySystem/Ability/BTSPlayerChangePerspective.h
  Source/BrutalTakedownSquad/Public/BTSGameplayTags.h
  Source/BrutalTakedownSquad/Public/Character/Player/BTSPlayer.h
Labels: bug, enhancement

#21 BehaivorTree 업데이트
  Content/Blueprints/AI/BP_BTSEnemy.uasset
  Content/Blueprints/AI/BTS_FindNearestPlayer.uasset
  Content/Blueprints/AI/BTService_FindNearestPlayer.uasset
  Content/Blueprints/AI/BT_EnemyBehaviorTree.uasset
  Source/BrutalTakedownSquad/Private/Character/Enemy/BTS_BTService_FindNearestPlayer.cpp
Labels: enhancement

#22 시점 전환 버그 수정
  BrutalTakedownSquad.uproject
  Content/Asset/Animation/Characters/Mannequins/Animations/ABP_Manny.uasset
  Content/Blueprints/AbilitySystem/Ability/GA_CharacterJump.uasset
  Content/Blueprints/AbilitySystem/Ability/GA_PlayerChagePerspective.uasset
  Content/Blueprints/AbilitySystem/Ability/GA_PlayerChangePerspective.uasset
  Content/Blueprints/Character/Player/BP_Player.uasset
  Content/Blueprints/Input/IMC_BTSInputContext.uasset
  Content/Levels/TempMat/Nimby.uasset
  Content/Levels/TempMat/Nimby_Mat.uasset
  Content/Levels/YWS_TestLevel.umap
  Source/BrutalTakedownSquad/Private/AbilitySystem/Ability/BTSCharacterJump.cpp
  Source/BrutalTakedownSquad/Private/AbilitySystem/Ability/BTSCharacterSprint.cpp
  Source/BrutalTakedownSquad/Private/AbilitySystem/Ability/BTSPlayerChangePerspective.cpp
  Source/BrutalTakedownSquad/Private/AbilitySystem/BTSAbilitySystemComponent.cpp
Labels: enhancement, BugFix

#23 Add TestUI Prototype
  Content/Blueprints/Game/BP_BTSGameMode.uasset
  Content/Blueprints/UI/TestPlayer/BP_TestPlayer.uasset
  Content/Blueprints/UI/TestPlayer/GM_TestUI.uasset
  Content/Blueprints/UI/TestPlayer/IA_Inventory.uasset
Labels: enhancement

#24 Add Inventory Widget
  Content/Blueprints/UI/BP_InventoryComponent.uasset
  Content/Blueprints/UI/Line.uasset
  Content/Blueprints/UI/SB_Color.uasset
  Content/Blueprints/UI/TestPlayer/BP_TestPlayer.uasset
  Content/Blueprints/UI/TestPlayer/IA_Inventory.uasset
  Content/Blueprints/UI/TestPlayer/IMC_Inventory.uasset
  Content/Blueprints/UI/Tile.uasset
  Content/Blueprints/UI/WBP_InventoryGridWidget.uasset
  Content/Blueprints/UI/WBP_InventoryWidget.uasset
  Content/Blueprints/UI/WBP_ItemWidget.uasset
  Content/Levels/TestUI.umap
Labels: enhancement

#25 AI 모션 추가 및 달리기상태 추가
  Content/Blueprints/AI/BP_BTSEnemy.uasset
  Content/Blueprints/AI/BTService_FindNearestPlayer.uasset
  Content/Levels/AiTestMap.umap
  Source/BrutalTakedownSquad/Public/Character/BTSCharacterBase.h
Labels: enhancement, BugFix

#26 CharacterAbility 클래스 추가
  Source/BrutalTakedownSquad/Private/AbilitySystem/Ability/BTSGameplayAbility.cpp
  Source/BrutalTakedownSquad/Private/AbilitySystem/Ability/Character/BTSCharacterCrouch.cpp
  Source/BrutalTakedownSquad/Private/AbilitySystem/Ability/Character/BTSCharacterGameplayAbility.cpp
  Source/BrutalTakedownSquad/Private/AbilitySystem/Ability/Character/BTSCharacterJump.cpp
  Source/BrutalTakedownSquad/Private/AbilitySystem/Ability/Character/BTSCharacterSprint.cpp
  Source/BrutalTakedownSquad/Private/AbilitySystem/Ability/Character/BTSPlayerChangePerspective.cpp
  Source/BrutalTakedownSquad/Private/AbilitySystem/BTSAttributeSet.cpp
  Source/BrutalTakedownSquad/Private/AbilitySystem/Data/AttributeInfo.cpp
  Source/BrutalTakedownSquad/Private/Character/Player/BTSPlayer.cpp
  Source/BrutalTakedownSquad/Private/Character/Player/BTSPlayerState.cpp
  Source/BrutalTakedownSquad/Public/AbilitySystem/Ability/Character/BTSCharacterCrouch.h
  Source/BrutalTakedownSquad/Public/AbilitySystem/Ability/Character/BTSCharacterGameplayAbility.h
  Source/BrutalTakedownSquad/Public/AbilitySystem/Ability/Character/BTSCharacterJump.h
  Source/BrutalTakedownSquad/Public/AbilitySystem/Ability/Character/BTSCharacterSprint.h
  Source/BrutalTakedownSquad/Public/AbilitySystem/Ability/Character/BTSPlayerChangePerspective.h
  Source/BrutalTakedownSquad/Public/AbilitySystem/Data/AttributeInfo.h
  Source/BrutalTakedownSquad/Public/Character/Player/BTSPlayerState.h
  Source/BrutalTakedownSquad/Public/Game/BTSGameModeBase.h
Labels: enhancement

#27 Turn In Place 기능 추가
  Content/Asset/Animation/Characters/Mannequins/Animations/ABP_Manny.uasset
  Content/Asset/Animation/Lyra_Anim/Unarmed_Animation/MM_Unarmed_TurnLeft_90.uasset
  Content/Asset/Animation/Lyra_Anim/Unarmed_Animation/MM_Unarmed_TurnRight_90.uasset
  Content/Blueprints/Character/Player/BP_Player.uasset
  Content/Levels/YWS_TestLevel.umap
Labels: enhancement

#32 근접 공격 능력 추가
  Content/Blueprints/AbilitySystem/Ability/GA_CharacterMelee.uasset
  Content/Blueprints/AbilitySystem/Effect/GE_Damage.uasset
  Content/Blueprints/Character/Player/BP_Player.uasset
  Content/Blueprints/Input/DA_BTSInputConfig.uasset
  Content/Blueprints/Input/IMC_BTSInputContext.uasset
  Content/Levels/YWS_TestLevel.umap
  Source/BrutalTakedownSquad/Private/AbilitySystem/Ability/Character/BTSCharacterMeleeAttack.cpp
  Source/BrutalTakedownSquad/Public/AbilitySystem/Ability/Character/BTSCharacterMeleeAttack.h
Labels: enhancement

#34 인벤토리 없는 파일 수정
  Content/Blueprints/UI/WBP_InventoryWidget.uasset
Labels: bug fix

#35 Weapon, item 추가
  Config/DefaultGameplayTags.ini
  Content/Levels/ItemTest.umap
  Content/Levels/ItemTestLevel.umap
  Source/BrutalTakedownSquad/Private/AbilitySystem/Ability/Weapon/BTS_GA_Weapon.cpp
  Source/BrutalTakedownSquad/Private/AbilitySystem/Ability/Weapon/BTS_GA_Weapon_ADS.cpp
  Source/BrutalTakedownSquad/Private/AbilitySystem/Ability/Weapon/BTS_GA_Weapon_Shoot.cpp
  Source/BrutalTakedownSquad/Private/Actor/BTS_Projectile.cpp
  Source/BrutalTakedownSquad/Private/Actor/Item/BTS_Item.cpp
  Source/BrutalTakedownSquad/Private/Actor/Item/Consumable/BTS_Item_WaterBottle.cpp
  Source/BrutalTakedownSquad/Private/Actor/Item/Weapon/BTS_Item_Weapon.cpp
  Source/BrutalTakedownSquad/Private/Actor/Item/Weapon/BTS_Item_Weapon_AR15.cpp
  Source/BrutalTakedownSquad/Private/BTSGameplayTags.cpp
  Source/BrutalTakedownSquad/Public/AbilitySystem/Ability/Weapon/BTS_GA_Weapon.h
  Source/BrutalTakedownSquad/Public/AbilitySystem/Ability/Weapon/BTS_GA_Weapon_ADS.h
  Source/BrutalTakedownSquad/Public/AbilitySystem/Ability/Weapon/BTS_GA_Weapon_Shoot.h
  Source/BrutalTakedownSquad/Public/AbilitySystem/Data/AttributeInfo.h
  Source/BrutalTakedownSquad/Public/Actor/BTS_Projectile.h
  Source/BrutalTakedownSquad/Public/Actor/Item/BTS_Item.h
  Source/BrutalTakedownSquad/Public/Actor/Item/Consumable/BTS_Item_WaterBottle.h
  Source/BrutalTakedownSquad/Public/Actor/Item/Weapon/BTS_Item_Weapon.h
  Source/BrutalTakedownSquad/Public/Actor/Item/Weapon/BTS_Item_Weapon_AR15.h
  Source/BrutalTakedownSquad/Public/BTSAssetManager.h
  Source/BrutalTakedownSquad/Public/BTSGameplayTags.h
Labels: enhancement

#36 AI 패턴 추가 및 맵 수정
  Content/Blueprints/AI/BP_AITest.uasset
  Content/Blueprints/AI/BP_AITestGamemode.uasset
  Content/Blueprints/AI/BP_BTSAIController.uasset
  Content/Blueprints/AI/BP_BTSEnemy.uasset
  Content/Blueprints/AI/BTService/BTService_SetSprint.uasset
  Content/Blueprints/AI/BTTask/BT_ClearRunaway.uasset
  Content/Blueprints/AI/BTTask/BT_SetBeforLocation.uasset
  Content/Blueprints/AI/BTTask/BT_SetBefore.uasset
  Content/Blueprints/AI/BTTask/BT_Setpreviouslyfledlocation.uasset
  Content/Blueprints/AI/BT_EnemyBehaviorTree.uasset
  Content/Blueprints/AI/GE_TestHeal.uasset
  Content/Levels/AiTestMap.umap
  Content/Levels/BTSMap.umap
  Content/Megascans/3D_Assets/Concrete_Stairs_uknjfevga/S_Concrete_Stairs_uknjfevga_lod5_Var1.uasset
  Source/BrutalTakedownSquad/Private/Character/Enemy/BTSEnemyBase.cpp
Labels: enhancement

#38 ADD Weapon pick up system
  Source/BrutalTakedownSquad/Private/Actor/Item/BTS_Item.cpp
  Source/BrutalTakedownSquad/Private/Actor/Item/Weapon/BTS_Item_Weapon.cpp
  Source/BrutalTakedownSquad/Private/Character/Enemy/BTSEnemyBase.cpp
  Source/BrutalTakedownSquad/Public/AbilitySystem/Ability/BTSGameplayAbility.h
  Source/BrutalTakedownSquad/Public/AbilitySystem/Ability/Character/BTSCharacterCrouch.h
  Source/BrutalTakedownSquad/Public/AbilitySystem/Ability/Character/BTSCharacterGameplayAbility.h
  Source/BrutalTakedownSquad/Public/AbilitySystem/Ability/Character/BTSCharacterJump.h
  Source/BrutalTakedownSquad/Public/AbilitySystem/Ability/Character/BTSCharacterSprint.h
  Source/BrutalTakedownSquad/Public/AbilitySystem/Ability/Character/BTSPlayerChangePerspective.h
  Source/BrutalTakedownSquad/Public/AbilitySystem/Ability/Weapon/BTS_GA_Weapon.h
  Source/BrutalTakedownSquad/Public/AbilitySystem/Ability/Weapon/BTS_GA_Weapon_ADS.h
  Source/BrutalTakedownSquad/Public/AbilitySystem/Ability/Weapon/BTS_GA_Weapon_Shoot.h
  Source/BrutalTakedownSquad/Public/AbilitySystem/BTSAbilitySystemComponent.h
  Source/BrutalTakedownSquad/Public/AbilitySystem/BTSAttributeSet.h
  Source/BrutalTakedownSquad/Public/Actor/BTS_Projectile.h
  Source/BrutalTakedownSquad/Public/Actor/Item/BTS_Item.h
  Source/BrutalTakedownSquad/Public/Actor/Item/Consumable/BTS_Item_WaterBottle.h
  Source/BrutalTakedownSquad/Public/Actor/Item/Weapon/BTS_Item_Weapon.h
  Source/BrutalTakedownSquad/Public/Actor/Item/Weapon/BTS_Item_Weapon_AR15.h
  Source/BrutalTakedownSquad/Public/BTSGameplayTags.h
  Source/BrutalTakedownSquad/Public/Character/Enemy/BTSAIController.h
  Source/BrutalTakedownSquad/Public/Character/Enemy/BTSEnemyBase.h
  Source/BrutalTakedownSquad/Public/Character/Enemy/BTS_BTService_FindNearestPlayer.h
  Source/BrutalTakedownSquad/Public/Character/Enemy/BTS_BTTask_GetRandomLocation.h
  Source/BrutalTakedownSquad/Public/Character/Player/BTSPlayer.h
  Source/BrutalTakedownSquad/Public/Character/Player/BTSPlayerController.h
  Source/BrutalTakedownSquad/Public/Character/Player/BTSPlayerState.h
  Source/BrutalTakedownSquad/Public/Game/BTSGameModeBase.h
  Source/BrutalTakedownSquad/Public/Input/BTSInputComponent.h
  Source/BrutalTakedownSquad/Public/Input/BTSInputConfig.h
Labels: enhancement

#43 UPDATE InventorySysterm Blueprint
  Content/Blueprints/UI/BP_InventoryGameState.uasset
  Content/Blueprints/UI/InventoryWidget/BP_InventoryComponent.uasset
  Content/Blueprints/UI/InventoryWidget/WBP_InventoryGridWidget.uasset
  Content/Blueprints/UI/InventoryWidget/WBP_InventoryWidget.uasset
  Content/Blueprints/UI/InventoryWidget/WBP_ItemWidget.uasset
  Content/Blueprints/UI/Item/BP_AK47.uasset
  Content/Blueprints/UI/Item/BP_AK47Test.uasset
  Content/Blueprints/UI/Item/BP_AK47_1.uasset
  Content/Blueprints/UI/Item/BP_Grenade.uasset
  Content/Blueprints/UI/Item/BP_ItemObject.uasset
  Content/Blueprints/UI/Item/BP_Knife.uasset
  Content/Blueprints/UI/TestPlayer/BP_TestPlayer.uasset
  Content/Blueprints/UI/TestPlayer/GM_TestUI.uasset
  Content/Levels/TestUI.umap
Labels: enhancement

#45 AI 숨기 및 공격기능 추가
  Config/DefaultEngine.ini
  Content/Blueprints/AI/BB_EnemyBlackboard.uasset
  Content/Blueprints/AI/BP_BTSEnemy.uasset
  Content/Blueprints/AI/BP_HideTest.uasset
  Content/Blueprints/AI/BP_TestEnemy.uasset
  Content/Blueprints/AI/BP_TextAIPlayer.uasset
  Content/Blueprints/AI/BTService/BTService_SetSprint.uasset
  Content/Blueprints/AI/BTTask/BT_GetPlayerLocation.uasset
  Content/Blueprints/AI/BTTask/BT_SetBeforLocation.uasset
  Content/Blueprints/AI/BTTask/BT_Shoot.uasset
  Content/Blueprints/AI/BT_EnemyBehaviorTree.uasset
  Content/Blueprints/AI/EQ/BP_EQSTestingPawn.uasset
  Content/Blueprints/AI/EQ/EQC_HideContext.uasset
  Content/Blueprints/AI/EQ/EQC_PlayerPosition.uasset
  Content/Blueprints/AI/EQ/EQ_FindHidePosision.uasset
  Content/Blueprints/Map/BP_Wall.uasset
  Content/Levels/AiTestMap.umap
  Content/Levels/BTSMap.umap
  Source/BrutalTakedownSquad/Private/Character/Enemy/BTS_BTTask_FindPlaceToHide.cpp
  Source/BrutalTakedownSquad/Public/Character/Enemy/BTS_BTTask_FindPlaceToHide.h
  Source/BrutalTakedownSquad/Public/Character/Enemy/BTS_BTTask_GetRandomLocation.h
Labels: enhancement

#46 FIX TestUI map
  Content/Blueprints/UI/TestPlayer/GM_TestUI.uasset
Labels: bug fix

#48 빌드 에러 핫픽스
  Source/BrutalTakedownSquad/Private/Actor/Item/BTS_Weapon.cpp
  Source/BrutalTakedownSquad/Public/Actor/Item/BTS_ItemInterface.h
Labels: bug

#58 Update inventory c++ converting
  BrutalTakedownSquad.uproject
  Content/Blueprints/UI/InventoryWidget/BP_InventoryComponent.uasset
  Content/Blueprints/UI/InventoryWidget/WBP_InventoryGridWidget.uasset
  Content/Blueprints/UI/Item/BP_AK47.uasset
  Content/Blueprints/UI/Item/BP_Item.uasset
  Source/BrutalTakedownSquad/Private/UI/InventoryUI/BTS_InventoryComponent.cpp
  Source/BrutalTakedownSquad/Private/UI/InventoryUI/BTS_InventoryGridWidget.cpp
  Source/BrutalTakedownSquad/Private/UI/InventoryUI/BTS_InventoryWidget.cpp
  Source/BrutalTakedownSquad/Private/UI/InventoryUI/BTS_ItemWidget.cpp
  Source/BrutalTakedownSquad/Private/UI/ItemUI/BTS_ItemObject.cpp
  Source/BrutalTakedownSquad/Public/UI/InventoryUI/BTS_InventoryComponent.h
  Source/BrutalTakedownSquad/Public/UI/InventoryUI/BTS_InventoryGridWidget.h
  Source/BrutalTakedownSquad/Public/UI/InventoryUI/BTS_InventoryWidget.h
  Source/BrutalTakedownSquad/Public/UI/InventoryUI/BTS_ItemWidget.h
  Source/BrutalTakedownSquad/Public/UI/InventoryUI/Line.h
  Source/BrutalTakedownSquad/Public/UI/InventoryUI/Tile.h
  Source/BrutalTakedownSquad/Public/UI/ItemUI/BTS_ItemObject.h
  Source/BrutalTakedownSquad/Public/UI/ItemUI/BTS_ItemUI.h
Labels: enhancement, bug fix
